codepkg/objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

codepkg/objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Sprints</relationshipLabel>
        <relationshipName>Sprints</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Sprint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/objects/Work_Item__c.object
<CustomObject>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>Work Items</relationshipLabel>
        <relationshipName>Work_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <inlineHelpText>Allowed values: 1, 2, 3, 5, 8, 13</inlineHelpText>
        <label>Story Points</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Work Item Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

codepkg/classes/WorkItemController.cls
public class WorkItemController {
	
    // combobox
    String status;
    public PageReference processRequest() {
        
        return null;
    }
    public List<SelectOption> getItems(){
        List<SelectOption> options = new List<SelectOption>();
        
        options.add(new SelectOption('NOT STARTED','Not Started'));
        options.add(new SelectOption('IN PROGRESS','In Progress'));
        options.add(new SelectOption('DONE','Done'));
        
        return options;
    }
    public String getStatus(){
        
        return status;
    }
    public void setStatus(String status){
        this.status = status;
    }
    
    private final Work_Item__c wi;
    
    public WorkItemController(ApexPages.StandardController stdController){
        stdController.addFields(new List<String>{'Story_Points__c','Sprint__r.Project__r.Id', 'Status__c'});        
        this.wi = (Work_Item__c)stdController.getRecord();
        system.debug(wi);
    }
    
    public List<Work_Item__c> getWorkItems(){
    	system.debug('el wi dentro del metodo '+wi.Story_Points__c);
        List<Work_Item__c> results = New List<Work_Item__c>();
        for(Work_Item__c w : [SELECT Id,Name FROM Work_Item__c WHERE Story_Points__c = :wi.Story_Points__c
                             AND Sprint__r.Project__r.Id = :wi.Sprint__r.Project__r.Id AND Status__c = :status]){
            results.add(w);
        }
    	return results;
    }   
}